import type { Locale } from "./i18n";
import type { EmployeeKey, LocalizedEmployeeDetail } from "./employee-catalog";

export type SupplementalEmployeeDetailRecord = {
  key: Exclude<EmployeeKey, "customer-support">;
  detail: Record<Locale, LocalizedEmployeeDetail>;
};

const administrative: SupplementalEmployeeDetailRecord = {
  key: "administrative",
  detail: {
    es: {
      slug: "administrativo",
      name: "Empleado IA Administrativo",
      shortName: "Administrativo IA",
      description: "Procesa correo, documentos, registros, formularios y seguimiento administrativo manteniendo trazabilidad y control humano en acciones relevantes.",
      department: "Administración",
      focus: "Documentos, registros y back office",
      statusLabel: "Perfil de referencia",
      cardCta: "Ver perfil completo",
      seoTitle: "Empleado IA Administrativo | IA Empleado",
      seoDescription: "Qué es un Empleado IA Administrativo, qué tareas de back office puede asumir, cómo trabaja con documentos, correo y ERP y qué acciones requieren supervisión humana.",
      eyebrow: "EMPLEADO IA · ADMINISTRACIÓN",
      heroTitle: "Administración que procesa, verifica y coordina trabajo sin perder trazabilidad.",
      heroDescription: "Un Empleado IA Administrativo puede absorber tareas repetitivas de back office, clasificar documentación, preparar registros y coordinar solicitudes internas dentro de permisos y políticas explícitas.",
      definitionTitle: "¿Qué es un Empleado IA Administrativo?",
      definitionBody: "Es un trabajador digital especializado en procesos administrativos acotados. Puede recibir correo y documentos, extraer información, validar si falta algo, preparar registros o formularios, actualizar sistemas autorizados y escalar decisiones o excepciones que la organización mantiene bajo control humano.",
      tasksTitle: "Tareas que puede asumir",
      tasks: [
        "Clasificar correo administrativo y derivarlo al proceso correcto.",
        "Leer documentos y extraer campos estructurados con trazabilidad de origen.",
        "Comprobar si una solicitud o expediente está completo.",
        "Preparar altas, formularios, fichas y borradores administrativos.",
        "Crear o actualizar registros en CRM, ERP o sistemas internos autorizados.",
        "Solicitar información o documentación que falta siguiendo plantillas aprobadas.",
        "Organizar documentos y tareas entre carpetas, expedientes o colas de trabajo.",
        "Detectar inconsistencias entre datos recibidos y registros existentes.",
        "Generar seguimientos, recordatorios y resúmenes operativos.",
      ],
      workflowTitle: "Cómo trabaja dentro de un proceso administrativo",
      workflowIntro: "El objetivo es reducir trabajo manual repetitivo sin convertir datos dudosos en información oficial ni ejecutar acciones fuera de autoridad.",
      workflow: [
        { title: "1. Recibe", text: "Entra un correo, documento, formulario o tarea desde un canal autorizado." },
        { title: "2. Extrae y clasifica", text: "Identifica el tipo de solicitud, extrae los campos necesarios y conserva la referencia a la fuente original." },
        { title: "3. Verifica", text: "Comprueba reglas de completitud, coincidencias y consistencia antes de preparar cambios en sistemas." },
        { title: "4. Ejecuta o coordina", text: "Actualiza registros de bajo riesgo cuando está autorizado o entrega la tarea a otro Empleado IA o a una persona." },
        { title: "5. Registra y sigue", text: "Deja historial, genera el siguiente recordatorio y mantiene el expediente preparado para continuar." },
      ],
      systemsTitle: "Sistemas con los que puede trabajar",
      systemsIntro: "El conjunto de conectores depende del proceso de cada empresa y de dónde reside la información administrativa.",
      systems: ["Email", "Gestor documental", "OCR", "CRM", "ERP", "Back office", "Formularios", "Hojas de cálculo", "APIs internas"],
      collaborationTitle: "El back office conecta departamentos",
      collaborationIntro: "Muchas tareas administrativas nacen en una solicitud de cliente, una venta, una factura o un proceso interno. El rol puede recibir y entregar trabajo estructurado a otros especialistas.",
      collaboration: [
        { title: "Con Atención al Cliente IA", text: "Para completar datos, tramitar documentación o resolver una gestión que empezó como una consulta de cliente." },
        { title: "Con Contabilidad y Facturación IA", text: "Para entregar facturas, datos fiscales, altas de proveedor o documentación que requiere validación financiera." },
        { title: "Con Comercial SDR IA", text: "Para preparar altas, documentación comercial, actualización de cuentas o seguimiento posterior a una oportunidad." },
        { title: "Con personas", text: "Para firmas, compromisos, excepciones, datos sensibles o decisiones que no deben automatizarse por defecto." },
      ],
      supervisionTitle: "Qué permanece bajo control humano",
      supervisionIntro: "Extraer o preparar información no equivale a tener autoridad para aprobarla, firmarla o convertirla automáticamente en un dato definitivo.",
      supervision: [
        "Firmas, compromisos contractuales o representaciones legales.",
        "Pagos, movimientos de dinero o autorizaciones financieras.",
        "Datos extraídos con baja confianza o documentos contradictorios.",
        "Cambios sensibles en registros cuando falta una coincidencia fiable.",
        "Cualquier proceso que la política interna reserve a revisión o aprobación humana.",
      ],
      useCasesTitle: "Ejemplos de uso",
      useCases: [
        { title: "Alta de cliente o proveedor", text: "Recibe documentación, comprueba campos obligatorios, prepara el registro y solicita los datos que faltan antes de una aprobación final." },
        { title: "Gestión de expedientes", text: "Clasifica documentos, mantiene una lista de pendientes y avisa cuando un expediente está listo para el siguiente paso." },
        { title: "Actualización de CRM o ERP", text: "Transforma información recibida en campos estructurados y propone o ejecuta actualizaciones dentro del alcance permitido." },
        { title: "Seguimiento administrativo", text: "Detecta tareas sin respuesta, envía recordatorios aprobados y actualiza el estado de la gestión." },
      ],
      sectorsTitle: "Dónde encaja especialmente bien",
      sectors: ["Servicios profesionales", "Distribución", "Ecommerce", "Turismo", "Gestorías y despachos", "Industria", "Empresas con alto volumen documental"],
      limitsTitle: "Lo que no debe prometerse",
      limits: [
        "No convierte automáticamente cualquier documento en un dato fiable sin validación.",
        "No firma contratos ni asume representación legal por defecto.",
        "No obtiene acceso general a todos los sistemas de la empresa; trabaja con permisos concretos.",
        "OCR, visión y automatización de navegador son capacidades opcionales según el proceso.",
        "La automatización real depende de la calidad documental, reglas, excepciones e integraciones disponibles.",
      ],
      faqTitle: "Preguntas frecuentes",
      faq: [
        { question: "¿Puede leer facturas, formularios o PDFs?", answer: "Sí cuando el despliegue incorpora comprensión documental u OCR. Los campos extraídos deben conservar procedencia y los valores con baja confianza pueden requerir revisión." },
        { question: "¿Puede actualizar un ERP automáticamente?", answer: "Puede hacerlo para operaciones autorizadas y de bajo riesgo cuando existe una integración y reglas claras. Otros cambios pueden quedar preparados para aprobación humana." },
        { question: "¿Sirve solo para grandes empresas?", answer: "No. También puede aportar valor en pymes con procesos repetitivos de correo, documentación y registro, siempre que el flujo pueda definirse con suficiente claridad." },
        { question: "¿Puede trabajar con otros Empleados IA?", answer: "Sí. Puede recibir trabajo desde Atención al Cliente o Ventas y entregar datos estructurados a Facturación, Reporting u otros roles especializados." },
        { question: "¿Qué ocurre si un documento está incompleto?", answer: "El flujo puede detectar campos ausentes, solicitar la información necesaria y dejar el expediente pendiente en vez de inventar o completar datos sin evidencia." },
      ],
      ctaEyebrow: "AUTOMATIZA EL BACK OFFICE",
      ctaTitle: "¿Qué proceso administrativo consume más tiempo cada semana?",
      ctaText: "Podemos mapear entradas, documentos, sistemas, validaciones y puntos de aprobación para identificar un primer flujo automatizable.",
      ctaPrimary: "Analizar mi proceso",
      ctaSecondary: "Ver todos los Empleados IA",
    },
    en: {
      slug: "administrative",
      name: "Administrative AI Employee",
      shortName: "Administrative AI",
      description: "Processes email, documents, records, forms and administrative follow-up while preserving traceability and human control over consequential actions.",
      department: "Administration",
      focus: "Documents, records and back office",
      statusLabel: "Reference profile",
      cardCta: "View full profile",
      seoTitle: "Administrative AI Employee | IA Empleado",
      seoDescription: "What an Administrative AI Employee is, which back-office tasks it can take on, how it works with documents, email and ERP systems, and what requires human supervision.",
      eyebrow: "AI EMPLOYEE · ADMINISTRATION",
      heroTitle: "Administration that processes, verifies and coordinates work without losing traceability.",
      heroDescription: "An Administrative AI Employee can absorb repetitive back-office work, classify documents, prepare records and coordinate internal requests within explicit permissions and policies.",
      definitionTitle: "What is an Administrative AI Employee?",
      definitionBody: "It is a digital worker specialized in bounded administrative processes. It can receive email and documents, extract information, check completeness, prepare records or forms, update authorized systems and escalate decisions or exceptions that the organization keeps under human control.",
      tasksTitle: "Tasks it can take on",
      tasks: [
        "Classify administrative email and route it to the right process.",
        "Read documents and extract structured fields while preserving source provenance.",
        "Check whether a request or case file is complete.",
        "Prepare registrations, forms, records and administrative drafts.",
        "Create or update records in authorized CRM, ERP or internal systems.",
        "Request missing information or documents using approved templates.",
        "Organize documents and tasks across folders, case files or work queues.",
        "Detect inconsistencies between received data and existing records.",
        "Generate follow-ups, reminders and operational summaries.",
      ],
      workflowTitle: "How it works inside an administrative process",
      workflowIntro: "The goal is to reduce repetitive manual work without turning uncertain data into official information or executing actions outside its authority.",
      workflow: [
        { title: "1. Receive", text: "An email, document, form or task arrives through an approved channel." },
        { title: "2. Extract and classify", text: "It identifies the request type, extracts required fields and keeps a reference to the original source." },
        { title: "3. Verify", text: "It checks completeness, matching and consistency rules before preparing changes in systems." },
        { title: "4. Execute or coordinate", text: "It updates low-risk records when authorized or hands the task to another AI Employee or a person." },
        { title: "5. Record and follow up", text: "It keeps history, schedules the next reminder and leaves the case ready to continue." },
      ],
      systemsTitle: "Systems it can work with",
      systemsIntro: "The connector set depends on each company process and where administrative information lives.",
      systems: ["Email", "Document management", "OCR", "CRM", "ERP", "Back office", "Forms", "Spreadsheets", "Internal APIs"],
      collaborationTitle: "Back office connects departments",
      collaborationIntro: "Many administrative tasks begin with a customer request, a sale, an invoice or an internal process. This role can receive and hand off structured work to other specialists.",
      collaboration: [
        { title: "With Customer Support AI", text: "To complete data, process documentation or resolve an administrative step that started as a customer request." },
        { title: "With Accounting & Billing AI", text: "To provide invoices, tax data, supplier registrations or documentation that needs financial validation." },
        { title: "With Sales SDR AI", text: "To prepare onboarding, commercial documentation, account updates or post-opportunity follow-up." },
        { title: "With people", text: "For signatures, commitments, exceptions, sensitive data or decisions that should not be automated by default." },
      ],
      supervisionTitle: "What remains under human control",
      supervisionIntro: "Extracting or preparing information is not the same as having authority to approve, sign or automatically make it authoritative.",
      supervision: [
        "Signatures, contractual commitments or legal representation.",
        "Payments, money movement or financial authorization.",
        "Low-confidence extracted data or contradictory documents.",
        "Sensitive record changes when there is no reliable match.",
        "Any process internal policy reserves for human review or approval.",
      ],
      useCasesTitle: "Example use cases",
      useCases: [
        { title: "Customer or supplier onboarding", text: "Receives documentation, checks mandatory fields, prepares the record and requests missing data before final approval." },
        { title: "Case-file management", text: "Classifies documents, maintains a pending-items list and signals when a case is ready for the next step." },
        { title: "CRM or ERP updates", text: "Transforms received information into structured fields and proposes or performs updates within the permitted scope." },
        { title: "Administrative follow-up", text: "Detects unanswered tasks, sends approved reminders and updates the status of the process." },
      ],
      sectorsTitle: "Where it fits especially well",
      sectors: ["Professional services", "Distribution", "Ecommerce", "Travel", "Administrative firms", "Industry", "Document-heavy organizations"],
      limitsTitle: "What should not be promised",
      limits: [
        "It does not automatically turn every document into reliable data without validation.",
        "It does not sign contracts or assume legal representation by default.",
        "It does not receive broad access to every company system; it works with specific permissions.",
        "OCR, vision and browser automation are optional capabilities depending on the process.",
        "Actual automation depends on document quality, rules, exceptions and available integrations.",
      ],
      faqTitle: "Frequently asked questions",
      faq: [
        { question: "Can it read invoices, forms or PDFs?", answer: "Yes when the deployment includes document understanding or OCR. Extracted fields should preserve provenance, and low-confidence values can require review." },
        { question: "Can it update an ERP automatically?", answer: "It can for authorized low-risk operations when an integration and clear rules exist. Other changes can be prepared for human approval." },
        { question: "Is it only useful for large companies?", answer: "No. It can also help smaller businesses with repetitive email, document and record work when the workflow can be defined clearly enough." },
        { question: "Can it work with other AI Employees?", answer: "Yes. It can receive work from Customer Support or Sales and hand structured data to Billing, Reporting or other specialist roles." },
        { question: "What happens when a document is incomplete?", answer: "The workflow can detect missing fields, request the needed information and keep the case pending instead of inventing or filling data without evidence." },
      ],
      ctaEyebrow: "AUTOMATE THE BACK OFFICE",
      ctaTitle: "Which administrative process consumes the most time every week?",
      ctaText: "We can map inputs, documents, systems, validations and approval points to identify a first workflow to automate.",
      ctaPrimary: "Analyze my process",
      ctaSecondary: "View all AI Employees",
    },
  },
};

const accountingBilling: SupplementalEmployeeDetailRecord = {
  key: "accounting-billing",
  detail: {
    es: {
      slug: "contabilidad-facturacion",
      name: "Empleado IA de Contabilidad y Facturación",
      shortName: "Contabilidad y Facturación IA",
      description: "Ayuda con entrada y validación de facturas, duplicados, vencimientos, conciliación básica, reporting y preparación de acciones para aprobación.",
      department: "Finanzas",
      focus: "Facturas, controles y seguimiento",
      statusLabel: "Perfil de referencia",
      cardCta: "Ver perfil completo",
      seoTitle: "Empleado IA de Contabilidad y Facturación | IA Empleado",
      seoDescription: "Qué puede hacer un Empleado IA de Contabilidad y Facturación con facturas, OCR, ERP, vencimientos y conciliación, y qué decisiones financieras deben seguir supervisadas.",
      eyebrow: "EMPLEADO IA · CONTABILIDAD Y FACTURACIÓN",
      heroTitle: "Facturación y contabilidad operativa con reglas, evidencia y aprobación donde importa.",
      heroDescription: "Un Empleado IA de Contabilidad y Facturación puede automatizar trabajo financiero repetitivo y comprobaciones operativas sin recibir por defecto autoridad para mover dinero, aprobar crédito o tomar decisiones financieras reguladas.",
      definitionTitle: "¿Qué es un Empleado IA de Contabilidad y Facturación?",
      definitionBody: "Es un trabajador digital especializado en tareas acotadas de facturación y soporte contable: recibe documentos, extrae campos, compara datos con sistemas autorizados, aplica controles deterministas, prepara registros y seguimientos y escala las acciones que requieren aprobación financiera o criterio profesional.",
      tasksTitle: "Tareas que puede asumir",
      tasks: [
        "Recibir facturas desde email, almacenamiento documental u otros canales autorizados.",
        "Extraer campos de facturas y documentos mediante comprensión documental u OCR.",
        "Relacionar proveedores, clientes, pedidos o registros existentes.",
        "Detectar posibles duplicados antes de registrar una factura.",
        "Comprobar campos contables o fiscales mediante reglas deterministas configuradas.",
        "Preparar borradores o registros de factura en ERP o software contable.",
        "Controlar vencimientos y preparar recordatorios de cobro o pago.",
        "Asistir en conciliaciones básicas comparando movimientos y documentos autorizados.",
        "Preparar reporting y acciones para revisión o aprobación humana.",
      ],
      workflowTitle: "Cómo trabaja dentro de un proceso financiero",
      workflowIntro: "El modelo puede interpretar documentos, pero los controles críticos y la autoridad financiera deben estar separados de la capacidad generativa.",
      workflow: [
        { title: "1. Recibe", text: "Captura la factura o documento desde una fuente permitida y conserva su origen." },
        { title: "2. Extrae y relaciona", text: "Obtiene campos relevantes y busca coincidencias de proveedor, cliente, pedido o cuenta en sistemas autorizados." },
        { title: "3. Comprueba", text: "Aplica reglas de duplicados, coherencia y campos obligatorios antes de preparar cualquier registro." },
        { title: "4. Prepara o registra", text: "Crea un borrador o ejecuta una operación permitida; las acciones de mayor impacto pasan a aprobación." },
        { title: "5. Sigue y reporta", text: "Actualiza estado, vencimientos, incidencias y métricas para que el proceso continúe con trazabilidad." },
      ],
      systemsTitle: "Sistemas con los que puede trabajar",
      systemsIntro: "Las integraciones financieras deben limitarse a las capacidades necesarias y pueden separar lectura, escritura y aprobación.",
      systems: ["Email", "OCR", "Gestor documental", "ERP", "Software contable", "CRM", "Ecommerce", "Banca en modo lectura", "APIs internas"],
      collaborationTitle: "Las finanzas reciben trabajo de toda la empresa",
      collaborationIntro: "Facturación rara vez empieza y termina en Finanzas. El rol puede recibir contexto de Ventas, Atención al Cliente o Administración y devolver un resultado estructurado.",
      collaboration: [
        { title: "Con Atención al Cliente IA", text: "Para revisar facturas incorrectas, estados de cobro o incidencias económicas relacionadas con un cliente." },
        { title: "Con Administrativo IA", text: "Para validar documentación, datos fiscales, altas y registros necesarios antes de contabilizar o facturar." },
        { title: "Con Comercial SDR IA", text: "Para aportar contexto de oportunidad, cliente, condiciones comerciales o información necesaria para preparar facturación." },
        { title: "Con personas", text: "Para aprobaciones, excepciones, cierres, criterio contable, movimientos de dinero o cualquier acción reservada por política." },
      ],
      supervisionTitle: "Qué permanece bajo control humano",
      supervisionIntro: "Una IA puede preparar trabajo contable sin asumir automáticamente autoridad financiera ni responsabilidad profesional.",
      supervision: [
        "Movimientos de dinero y pagos fuera de cualquier alcance autónomo por defecto.",
        "Aprobaciones financieras relevantes o cambios de condiciones económicas.",
        "Decisiones de crédito, riesgo, elegibilidad o scoring sobre personas.",
        "Casos contables o fiscales ambiguos que requieren criterio profesional.",
        "Registros con datos contradictorios, coincidencias dudosas o excepciones fuera de política.",
      ],
      useCasesTitle: "Ejemplos de uso",
      useCases: [
        { title: "Entrada de factura de proveedor", text: "Extrae datos, identifica proveedor, comprueba duplicados y prepara el registro para revisión o contabilización según permisos." },
        { title: "Factura reclamada por un cliente", text: "Recibe contexto desde Atención al Cliente, compara factura y pedido y prepara una corrección o la escalada adecuada." },
        { title: "Control de vencimientos", text: "Identifica facturas próximas o vencidas y prepara recordatorios y estados sin asumir decisiones de cobro extraordinarias." },
        { title: "Conciliación asistida", text: "Compara información disponible y propone coincidencias, dejando las discrepancias o casos de baja confianza para revisión." },
      ],
      sectorsTitle: "Dónde encaja especialmente bien",
      sectors: ["Ecommerce", "Retail", "Servicios B2B", "Distribución", "Turismo", "Industria", "Empresas con alto volumen de facturas"],
      limitsTitle: "Lo que no debe prometerse",
      limits: [
        "No sustituye automáticamente el criterio de un profesional contable o fiscal.",
        "No mueve dinero ni aprueba pagos por el simple hecho de procesar facturas.",
        "No realiza decisiones reguladas de crédito, riesgo o elegibilidad como extensión de este perfil.",
        "Los controles contables relevantes deben apoyarse en reglas deterministas cuando sea posible.",
        "El alcance depende de integraciones, calidad documental, políticas y excepciones de cada organización.",
      ],
      faqTitle: "Preguntas frecuentes",
      faq: [
        { question: "¿Puede leer facturas escaneadas?", answer: "Sí cuando el despliegue incluye OCR o comprensión documental. Los valores extraídos conservan procedencia y pueden requerir revisión si la confianza es insuficiente." },
        { question: "¿Puede contabilizar facturas directamente?", answer: "Puede preparar o ejecutar registros concretos si la política, permisos e integración lo autorizan. La autoridad de aprobación se configura por separado." },
        { question: "¿Puede acceder al banco?", answer: "Puede existir una integración de solo lectura para determinados procesos. El movimiento de dinero no forma parte de la autoridad autónoma por defecto." },
        { question: "¿Puede detectar duplicados?", answer: "Sí, combinando identificadores, importes, fechas, proveedores y reglas del sistema. Los casos ambiguos pueden quedar marcados para revisión." },
        { question: "¿Es lo mismo que una IA que decide créditos?", answer: "No. Facturación y soporte contable son distintos de decisiones financieras de crédito, riesgo o elegibilidad, que pueden ser reguladas y no se habilitan como una extensión genérica de este perfil." },
      ],
      ctaEyebrow: "AUTOMATIZA EL FLUJO FINANCIERO",
      ctaTitle: "¿Dónde se acumula hoy el trabajo repetitivo de facturación?",
      ctaText: "Podemos revisar entrada de documentos, ERP, controles, vencimientos y aprobaciones para definir un primer flujo seguro.",
      ctaPrimary: "Analizar mi proceso",
      ctaSecondary: "Ver todos los Empleados IA",
    },
    en: {
      slug: "accounting-billing",
      name: "Accounting & Billing AI Employee",
      shortName: "Accounting & Billing AI",
      description: "Helps with invoice intake and validation, duplicate checks, due dates, basic reconciliation, reporting and preparation of actions for approval.",
      department: "Finance",
      focus: "Invoices, controls and follow-up",
      statusLabel: "Reference profile",
      cardCta: "View full profile",
      seoTitle: "Accounting & Billing AI Employee | IA Empleado",
      seoDescription: "What an Accounting & Billing AI Employee can do with invoices, OCR, ERP systems, due dates and reconciliation, and which financial decisions should remain supervised.",
      eyebrow: "AI EMPLOYEE · ACCOUNTING & BILLING",
      heroTitle: "Operational accounting and billing with rules, evidence and approval where it matters.",
      heroDescription: "An Accounting & Billing AI Employee can automate repetitive finance work and operational checks without receiving default authority to move money, approve credit or make regulated financial decisions.",
      definitionTitle: "What is an Accounting & Billing AI Employee?",
      definitionBody: "It is a digital worker specialized in bounded billing and accounting-support tasks: receiving documents, extracting fields, comparing data with authorized systems, applying deterministic controls, preparing records and follow-up, and escalating actions that require financial approval or professional judgment.",
      tasksTitle: "Tasks it can take on",
      tasks: [
        "Receive invoices from email, document storage or other authorized channels.",
        "Extract invoice and document fields through document understanding or OCR.",
        "Match suppliers, customers, orders or existing records.",
        "Detect possible duplicates before invoice registration.",
        "Check accounting or tax-related fields through configured deterministic rules.",
        "Prepare invoice drafts or records in ERP or accounting software.",
        "Track due dates and prepare payment or collection reminders.",
        "Assist with basic reconciliation by comparing authorized transactions and documents.",
        "Prepare reporting and actions for human review or approval.",
      ],
      workflowTitle: "How it works inside a finance process",
      workflowIntro: "The model can interpret documents, but critical controls and financial authority should remain separate from generative capability.",
      workflow: [
        { title: "1. Receive", text: "Captures the invoice or document from an approved source and preserves its origin." },
        { title: "2. Extract and match", text: "Gets relevant fields and searches for supplier, customer, order or account matches in authorized systems." },
        { title: "3. Check", text: "Applies duplicate, consistency and mandatory-field rules before preparing any record." },
        { title: "4. Prepare or register", text: "Creates a draft or performs a permitted operation; higher-impact actions move to approval." },
        { title: "5. Follow up and report", text: "Updates status, due dates, incidents and metrics so the process continues with traceability." },
      ],
      systemsTitle: "Systems it can work with",
      systemsIntro: "Finance integrations should be restricted to required capabilities and can separate read, write and approval authority.",
      systems: ["Email", "OCR", "Document management", "ERP", "Accounting software", "CRM", "Ecommerce", "Read-only banking", "Internal APIs"],
      collaborationTitle: "Finance receives work from across the company",
      collaborationIntro: "Billing rarely starts and ends inside Finance. The role can receive context from Sales, Customer Support or Administration and return a structured result.",
      collaboration: [
        { title: "With Customer Support AI", text: "To review incorrect invoices, payment status or customer-facing financial incidents." },
        { title: "With Administrative AI", text: "To validate documents, tax data, onboarding and records needed before invoicing or accounting." },
        { title: "With Sales SDR AI", text: "To receive opportunity, customer or commercial-condition context needed to prepare billing." },
        { title: "With people", text: "For approvals, exceptions, closing, professional accounting judgment, money movement or any action reserved by policy." },
      ],
      supervisionTitle: "What remains under human control",
      supervisionIntro: "AI can prepare accounting work without automatically assuming financial authority or professional responsibility.",
      supervision: [
        "Money movement and payments outside autonomous authority by default.",
        "Consequential financial approvals or changes to commercial terms.",
        "Credit, risk, eligibility or scoring decisions affecting people.",
        "Ambiguous accounting or tax cases requiring professional judgment.",
        "Records with contradictory data, uncertain matches or exceptions outside policy.",
      ],
      useCasesTitle: "Example use cases",
      useCases: [
        { title: "Supplier invoice intake", text: "Extracts data, identifies the supplier, checks duplicates and prepares the record for review or registration according to permissions." },
        { title: "Customer invoice dispute", text: "Receives context from Customer Support, compares invoice and order data, and prepares a correction or appropriate escalation." },
        { title: "Due-date control", text: "Identifies upcoming or overdue invoices and prepares reminders and statuses without assuming exceptional collection decisions." },
        { title: "Assisted reconciliation", text: "Compares available information and proposes matches, leaving discrepancies or low-confidence cases for review." },
      ],
      sectorsTitle: "Where it fits especially well",
      sectors: ["Ecommerce", "Retail", "B2B services", "Distribution", "Travel", "Industry", "High-invoice-volume organizations"],
      limitsTitle: "What should not be promised",
      limits: [
        "It does not automatically replace professional accounting or tax judgment.",
        "It does not move money or approve payments simply because it processes invoices.",
        "It does not perform regulated credit, risk or eligibility decisions as an extension of this profile.",
        "Relevant accounting controls should use deterministic rules where possible.",
        "Scope depends on integrations, document quality, policies and each organization’s exceptions.",
      ],
      faqTitle: "Frequently asked questions",
      faq: [
        { question: "Can it read scanned invoices?", answer: "Yes when the deployment includes OCR or document understanding. Extracted values preserve provenance and can require review when confidence is insufficient." },
        { question: "Can it post invoices directly?", answer: "It can prepare or execute specific records when policy, permissions and integration authorize it. Approval authority is configured separately." },
        { question: "Can it access a bank account?", answer: "A read-only integration can exist for specific processes. Money movement is not part of default autonomous authority." },
        { question: "Can it detect duplicates?", answer: "Yes, using identifiers, amounts, dates, suppliers and system rules. Ambiguous cases can be flagged for review." },
        { question: "Is this the same as AI making credit decisions?", answer: "No. Billing and accounting support are distinct from credit, risk or eligibility decisions, which may be regulated and are not enabled as a generic extension of this profile." },
      ],
      ctaEyebrow: "AUTOMATE THE FINANCE FLOW",
      ctaTitle: "Where does repetitive billing work accumulate today?",
      ctaText: "We can review document intake, ERP systems, controls, due dates and approvals to define a safe first workflow.",
      ctaPrimary: "Analyze my process",
      ctaSecondary: "View all AI Employees",
    },
  },
};

const salesSdr: SupplementalEmployeeDetailRecord = {
  key: "sales-sdr",
  detail: {
    es: {
      slug: "comercial-sdr",
      name: "Empleado IA Comercial SDR",
      shortName: "Comercial SDR IA",
      description: "Apoya investigación aprobada, higiene de CRM, cualificación, preparación de outreach, seguimiento y coordinación de reuniones bajo reglas de canal y supervisión.",
      department: "Ventas",
      focus: "Prospección, CRM y seguimiento",
      statusLabel: "Perfil de referencia",
      cardCta: "Ver perfil completo",
      seoTitle: "Empleado IA Comercial SDR | IA Empleado",
      seoDescription: "Qué puede hacer un Empleado IA Comercial SDR en prospección, CRM, investigación, seguimiento y reuniones, y cómo limitar outreach, permisos y supervisión.",
      eyebrow: "EMPLEADO IA · VENTAS / SDR",
      heroTitle: "Prospección y seguimiento comercial sistemáticos, con contexto y reglas de canal.",
      heroDescription: "Un Empleado IA Comercial SDR puede ampliar la capacidad de ventas investigando cuentas, manteniendo el CRM, preparando outreach y coordinando seguimientos sin asumir libertad ilimitada para contactar, prometer o modificar condiciones comerciales.",
      definitionTitle: "¿Qué es un Empleado IA Comercial SDR?",
      definitionBody: "Es un trabajador digital especializado en tareas acotadas de desarrollo comercial. Puede investigar empresas usando fuentes aprobadas, enriquecer CRM, aplicar criterios de cualificación, preparar mensajes personalizados, clasificar respuestas y coordinar reuniones dentro de políticas de privacidad, canal y supervisión.",
      tasksTitle: "Tareas que puede asumir",
      tasks: [
        "Investigar empresas y cuentas usando fuentes permitidas.",
        "Crear o enriquecer leads y cuentas en el CRM con datos verificables.",
        "Resumir contexto de empresa, contacto y oportunidad para el equipo comercial.",
        "Aplicar criterios de cualificación definidos por negocio.",
        "Preparar mensajes de prospección personalizados a partir de información aprobada.",
        "Enviar outreach cuando la política de canal y el despliegue lo permitan.",
        "Clasificar respuestas y detectar interés, objeciones o solicitudes de baja.",
        "Programar seguimientos y mantener higiene del pipeline.",
        "Coordinar reuniones y preparar un briefing para la persona comercial.",
      ],
      workflowTitle: "Cómo trabaja dentro de un proceso comercial",
      workflowIntro: "La velocidad comercial solo aporta valor si los datos son fiables, el canal está autorizado y el historial queda registrado.",
      workflow: [
        { title: "1. Identifica", text: "Recibe una lista, segmento o criterio de cuenta y determina qué información puede consultar." },
        { title: "2. Investiga", text: "Reúne contexto desde fuentes aprobadas y evita convertir inferencias no confirmadas en hechos." },
        { title: "3. Cualifica", text: "Aplica criterios de negocio y actualiza el CRM con razones y evidencia disponible." },
        { title: "4. Contacta o prepara", text: "Genera outreach y lo envía solo cuando la política lo permite; si no, lo deja listo para revisión." },
        { title: "5. Sigue y entrega", text: "Clasifica respuestas, agenda el siguiente paso y entrega oportunidades maduras con un briefing estructurado." },
      ],
      systemsTitle: "Sistemas con los que puede trabajar",
      systemsIntro: "Ventas suele requerir pocos sistemas, pero deben estar bien gobernados para evitar outreach descontrolado o datos inventados.",
      systems: ["CRM", "Email", "Calendario", "Fuentes de investigación aprobadas", "Formularios", "Telefonía opcional", "Base de conocimiento", "APIs comerciales"],
      collaborationTitle: "Ventas activa procesos posteriores",
      collaborationIntro: "Una oportunidad comercial genera tareas administrativas, documentación, facturación y atención. El Empleado IA puede entregar contexto sin obligar a cada departamento a reconstruirlo.",
      collaboration: [
        { title: "Con Administrativo IA", text: "Para preparar altas, documentación, datos de cuenta y tareas de back office cuando una oportunidad avanza." },
        { title: "Con Contabilidad y Facturación IA", text: "Para transferir datos necesarios para presupuestos, facturación o validaciones sin conceder autoridad financiera al rol comercial." },
        { title: "Con Atención al Cliente IA", text: "Para entregar contexto de cliente cuando una oportunidad pasa a onboarding, servicio o soporte." },
        { title: "Con personas", text: "Para negociación, compromisos, condiciones especiales, oportunidades estratégicas o cualquier mensaje que requiera revisión." },
      ],
      supervisionTitle: "Qué permanece bajo control humano",
      supervisionIntro: "Automatizar prospección no significa permitir contacto ilimitado ni decisiones comerciales sin política.",
      supervision: [
        "Volumen, dominios, geografía, horarios y canales de outreach.",
        "Mensajes o campañas que la empresa decida revisar antes del envío.",
        "Precios, descuentos, compromisos contractuales y condiciones especiales.",
        "Datos personales o fuentes cuya utilización no esté aprobada para prospección.",
        "Oportunidades estratégicas, excepciones y negociaciones que requieren criterio humano.",
      ],
      useCasesTitle: "Ejemplos de uso",
      useCases: [
        { title: "Preparación de cuenta", text: "Recopila información autorizada, resume contexto y crea una ficha útil antes de que una persona contacte con la empresa." },
        { title: "Higiene de CRM", text: "Detecta campos incompletos, duplica menos trabajo, actualiza estados y prepara tareas de seguimiento según reglas." },
        { title: "Seguimiento sistemático", text: "Programa y prepara contactos posteriores según la respuesta anterior y el estado de la oportunidad." },
        { title: "Reserva de reunión", text: "Cuando existe interés, propone horarios autorizados, registra la reunión y entrega un briefing al responsable comercial." },
      ],
      sectorsTitle: "Dónde encaja especialmente bien",
      sectors: ["Servicios B2B", "Software y SaaS", "Agencias", "Industria", "Distribución", "Consultoría", "Empresas con venta consultiva o pipeline estructurado"],
      limitsTitle: "Lo que no debe prometerse",
      limits: [
        "No debe inventar datos sobre empresas, contactos o necesidades no confirmadas.",
        "No debe enviar outreach sin límites de volumen, canal, geografía y política.",
        "No sustituye por defecto negociación, cierre ni decisiones comerciales relevantes.",
        "La investigación mediante navegador o fuentes externas es una capacidad opcional y gobernada.",
        "El cumplimiento de privacidad y marketing directo debe evaluarse según mercado, fuente y caso de uso.",
      ],
      faqTitle: "Preguntas frecuentes",
      faq: [
        { question: "¿Puede buscar clientes potenciales por Internet?", answer: "Puede usar investigación web cuando esa capacidad está habilitada y las fuentes están aprobadas. Los datos obtenidos deben tratarse según las reglas de privacidad y marketing aplicables." },
        { question: "¿Puede enviar emails automáticamente?", answer: "Puede hacerlo cuando la política de canal lo autoriza. El volumen, dominios, geografía, horarios y necesidad de revisión humana pueden limitarse explícitamente." },
        { question: "¿Puede decidir si un lead es bueno?", answer: "Puede aplicar criterios deterministas de cualificación definidos por la empresa y aportar contexto. Eso no equivale a una autoridad comercial ilimitada ni a decisiones reguladas sobre personas." },
        { question: "¿Puede reservar reuniones?", answer: "Sí cuando existe acceso autorizado al calendario y reglas sobre disponibilidad. La reunión y el contexto pueden quedar registrados automáticamente en el CRM." },
        { question: "¿Puede trabajar con otros Empleados IA?", answer: "Sí. Cuando una oportunidad avanza puede entregar tareas y contexto a Administración, Facturación, Atención al Cliente u otros roles, manteniendo los permisos de cada uno." },
      ],
      ctaEyebrow: "AUMENTA LA CAPACIDAD COMERCIAL",
      ctaTitle: "¿Qué parte de tu prospección y seguimiento sigue siendo manual?",
      ctaText: "Podemos revisar CRM, fuentes, canales, criterios de cualificación y puntos de revisión para diseñar un primer flujo comercial gobernado.",
      ctaPrimary: "Analizar mi proceso",
      ctaSecondary: "Ver todos los Empleados IA",
    },
    en: {
      slug: "sales-sdr",
      name: "Sales / SDR AI Employee",
      shortName: "Sales SDR AI",
      description: "Supports approved research, CRM hygiene, qualification, outreach preparation, follow-up and meeting coordination under channel and supervision policies.",
      department: "Sales",
      focus: "Prospecting, CRM and follow-up",
      statusLabel: "Reference profile",
      cardCta: "View full profile",
      seoTitle: "Sales SDR AI Employee | IA Empleado",
      seoDescription: "What a Sales SDR AI Employee can do across prospecting, CRM, research, follow-up and meetings, and how outreach, permissions and supervision remain controlled.",
      eyebrow: "AI EMPLOYEE · SALES / SDR",
      heroTitle: "Systematic prospecting and follow-up with context and channel rules.",
      heroDescription: "A Sales SDR AI Employee can expand sales capacity by researching accounts, maintaining CRM data, preparing outreach and coordinating follow-up without receiving unlimited freedom to contact, promise or change commercial terms.",
      definitionTitle: "What is a Sales SDR AI Employee?",
      definitionBody: "It is a digital worker specialized in bounded sales-development tasks. It can research companies using approved sources, enrich CRM records, apply qualification criteria, prepare personalized messages, classify replies and coordinate meetings within privacy, channel and supervision policies.",
      tasksTitle: "Tasks it can take on",
      tasks: [
        "Research companies and accounts using approved sources.",
        "Create or enrich CRM leads and accounts with verifiable information.",
        "Summarize company, contact and opportunity context for the sales team.",
        "Apply qualification criteria defined by the business.",
        "Prepare personalized prospecting messages from approved information.",
        "Send outreach when channel policy and deployment permissions allow it.",
        "Classify replies and identify interest, objections or opt-out requests.",
        "Schedule follow-up and maintain pipeline hygiene.",
        "Coordinate meetings and prepare a briefing for the salesperson.",
      ],
      workflowTitle: "How it works inside a sales process",
      workflowIntro: "Sales speed only creates value when data is reliable, the channel is authorized and the activity history is recorded.",
      workflow: [
        { title: "1. Identify", text: "Receives a list, segment or account criterion and determines which information it is allowed to consult." },
        { title: "2. Research", text: "Collects context from approved sources and avoids turning unconfirmed inference into fact." },
        { title: "3. Qualify", text: "Applies business criteria and updates the CRM with available reasoning and evidence." },
        { title: "4. Contact or prepare", text: "Creates outreach and sends it only when policy permits; otherwise it leaves the message ready for review." },
        { title: "5. Follow up and hand off", text: "Classifies replies, schedules the next step and hands mature opportunities to a person with a structured briefing." },
      ],
      systemsTitle: "Systems it can work with",
      systemsIntro: "Sales often needs only a few systems, but they must be governed to prevent uncontrolled outreach or invented data.",
      systems: ["CRM", "Email", "Calendar", "Approved research sources", "Forms", "Optional telephony", "Knowledge base", "Sales APIs"],
      collaborationTitle: "Sales activates downstream processes",
      collaborationIntro: "A sales opportunity creates administrative, documentation, billing and service work. The AI Employee can hand off context without forcing each department to rebuild it.",
      collaboration: [
        { title: "With Administrative AI", text: "To prepare onboarding, documentation, account data and back-office tasks when an opportunity advances." },
        { title: "With Accounting & Billing AI", text: "To pass data needed for quotes, billing or validation without giving financial authority to the sales role." },
        { title: "With Customer Support AI", text: "To hand over customer context when an opportunity moves into onboarding, service or support." },
        { title: "With people", text: "For negotiation, commitments, special terms, strategic opportunities or any message that requires review." },
      ],
      supervisionTitle: "What remains under human control",
      supervisionIntro: "Automating prospecting does not mean allowing unlimited contact or commercial decisions without policy.",
      supervision: [
        "Outreach volume, domains, geography, timing and channels.",
        "Messages or campaigns the company chooses to review before sending.",
        "Pricing, discounts, contractual commitments and special terms.",
        "Personal data or sources not approved for prospecting use.",
        "Strategic opportunities, exceptions and negotiations requiring human judgment.",
      ],
      useCasesTitle: "Example use cases",
      useCases: [
        { title: "Account preparation", text: "Collects authorized information, summarizes context and creates a useful account brief before a person contacts the company." },
        { title: "CRM hygiene", text: "Finds incomplete fields, reduces duplicate work, updates statuses and prepares follow-up tasks according to rules." },
        { title: "Systematic follow-up", text: "Schedules and prepares subsequent contact based on the previous reply and current opportunity state." },
        { title: "Meeting booking", text: "When interest exists, proposes approved times, records the meeting and hands a briefing to the responsible salesperson." },
      ],
      sectorsTitle: "Where it fits especially well",
      sectors: ["B2B services", "Software and SaaS", "Agencies", "Industry", "Distribution", "Consulting", "Structured pipeline or consultative sales teams"],
      limitsTitle: "What should not be promised",
      limits: [
        "It must not invent facts about companies, contacts or needs that are not confirmed.",
        "It must not send outreach without limits on volume, channel, geography and policy.",
        "It does not replace negotiation, closing or consequential commercial decisions by default.",
        "Browser research or external-source research is an optional, governed capability.",
        "Privacy and direct-marketing requirements must be evaluated by market, source and use case.",
      ],
      faqTitle: "Frequently asked questions",
      faq: [
        { question: "Can it find prospects on the Internet?", answer: "It can use web research when that capability is enabled and the sources are approved. Collected data must be handled according to applicable privacy and marketing rules." },
        { question: "Can it send emails automatically?", answer: "It can when channel policy authorizes it. Volume, domains, geography, timing and human-review requirements can all be explicitly limited." },
        { question: "Can it decide whether a lead is good?", answer: "It can apply deterministic qualification criteria defined by the company and provide context. That does not imply unlimited commercial authority or regulated decisions about people." },
        { question: "Can it book meetings?", answer: "Yes when it has authorized calendar access and availability rules. The meeting and context can also be recorded in the CRM." },
        { question: "Can it work with other AI Employees?", answer: "Yes. When an opportunity advances it can hand tasks and context to Administration, Billing, Customer Support or other roles while preserving each role’s permissions." },
      ],
      ctaEyebrow: "EXPAND SALES CAPACITY",
      ctaTitle: "Which part of prospecting and follow-up is still manual?",
      ctaText: "We can review CRM, sources, channels, qualification criteria and review points to design a first governed sales workflow.",
      ctaPrimary: "Analyze my process",
      ctaSecondary: "View all AI Employees",
    },
  },
};

export const supplementalEmployeeDetails: SupplementalEmployeeDetailRecord[] = [
  administrative,
  accountingBilling,
  salesSdr,
];

export function getSupplementalEmployeeBySlug(locale: Locale, slug: string) {
  const employee = supplementalEmployeeDetails.find((item) => item.detail[locale].slug === slug);
  if (!employee) return null;
  return {
    key: employee.key,
    availability: "reference" as const,
    content: employee.detail[locale],
    alternate: employee.detail[locale === "es" ? "en" : "es"],
  };
}

export function supplementalEmployeeDetailPath(key: EmployeeKey, locale: Locale) {
  const employee = supplementalEmployeeDetails.find((item) => item.key === key);
  if (!employee) return null;
  const slug = employee.detail[locale].slug;
  return locale === "es" ? `/empleados-ia/${slug}` : `/en/ai-employees/${slug}`;
}
