// Generated by scripts/generate-release-fingerprint.mjs before production builds.
// The committed fallback keeps typecheck/dev usable before the build lifecycle runs.
export const WEB_RELEASE_FINGERPRINT = "web-dev-unbuilt" as const;
